# Generated by Django 3.2.7 on 2021-09-15 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenft',
            name='profile',
        ),
        migrations.AddField(
            model_name='imagenft',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
