# Generated by Django 3.2.7 on 2021-09-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileUser', '0002_auto_20210915_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenft',
            old_name='user',
            new_name='author',
        ),
    ]
